
#
#    ____
#   / ___|   _  __ _ _ __  _   _  __ _  ___ _ __
#  | |  | | | |/ _` | '_ \| | | |/ _` |/ _ \ '_ \
#  | |__| |_| | (_| | | | | |_| | (_| |  __/ | | |
#   \____\__, |\__,_|_| |_|\__,_|\__, |\___|_| |_|
#        |___/                   |___/ Pro
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# @author zsTr3mx_ (@zstr3mx_dev)
#

messages:
  welcome: "§8× §fWelcome to the server with §dCyanugen CLIENT_VERSION§f."
  scripts_enabled: "§8× §fEnabling support for your §bClient §fscripts..."

settings:
  username_edit: false
  scripting_enabled: false
  
# Don't modify it if you don't know what you're doing.
packets:
  version_packet: "§c§y§l§s§s" #cylss
  join_packet: "§c§y§l§s§r" #cylsr
  script_packet: "§c§y§e§s§r" #cyesr
